language: python
python:
  - 3.6
before_install:
  - pip install codecov
  - pip install pytest-cov
  - pip install sphinx_rtd_theme
  - pip install numpydoc
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest

after_success:
  - codecov
